# Pandas 1

## Bryant McArthur

## Math 403

## August 30, 2022

In [1]:
import numpy as np
import pandas as pd

# Problem 1

In [21]:
# Prob 1
def prob1(file='budget.csv'):
    """"
    Read in budget.csv as a DataFrame with the index as column 0 and perform each of these operations on the DataFrame in order. 
    
    1) Reindex the columns such that amount spent on groceries is the first column and all other columns maintain the same ordering.
    2) Sort the DataFrame in descending order based on how much money was spent on Groceries.
    3) Reset all values in the 'Rent' column to 800.0.
    4) Reset all values in the first 5 data points to 0.0
    
    Return the values of the updated DataFrame as a NumPy array.
    
    Parameters:
        file (str): name of datafile
        
    Return:
        values (ndarray): values of DataFrame
    """
    # Read in the CSV file
    budget = pd.read_csv(file, index_col=0)
    
    #Manipulate according to steps above
    budget = budget.reindex(columns=['Groceries','Rent','Utilities','Dining Out','Gas','Out With Friends', 'Netflix'])
    budget = budget.sort_values('Groceries', ascending=False)
    budget['Rent'] = 800.0
    budget.iloc[:5, :] = 0.0
    
    return budget.values
    
budget = prob1()
print(budget)

[[  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.]
 [174. 800.  90.  37.  30.  23.   8.]
 [174. 800.  82.  35.  nan  26.  nan]
 [172. 800.  82.  31.  30.  26.   8.]
 [171. 800.  82.  40.  nan  23.  nan]
 [171. 800.  82.  35.  nan  27.  nan]
 [171. 800.  80.  30.  31.  22.  nan]
 [170. 800.  90.  34.  33.  nan   8.]
 [170. 800.  85.  34.  nan  25.  nan]
 [167. 800.  92.  30.  nan  29.  nan]
 [163. 800.  85.  30.  nan  nan  nan]
 [163. 800.  90.  31.  nan  25.  nan]
 [161. 800.  85.  30.  nan  24.  nan]
 [160. 800.  91.  32.  28.  23.  nan]
 [158. 800.  92.  nan  nan  22.  nan]
 [157. 800.  82.  nan  32.  21.   8.]
 [155. 800.  80.  nan  33.  26.   8.]
 [155. 800.  92.  33.  nan  nan  nan]
 [153. 800.  80.  31.  30.  27.   8.]
 [152. 800.  95.  30.  46.  nan   8.]
 [152. 800.  85.  39.  nan  29.  nan]
 [152. 800.  95.  32.  34.  22.   8.]
 [150. 800. 

# Problem 2

In [53]:
# Prob 2
def prob2(file='budget.csv'):
    """
    Read in file as DataFrame.
    Fill all NaN values with 0.0.
    Create two new columns, 'Living Expenses' and 'Other'. 
    Sum the columns 'Rent', 'Groceries', 'Gas' and 'Utilities' and set it as the value of 'Living Expenses'.
    Sum the columns 'Dining Out', 'Out With Friends' and 'Netflix' and set as the value of 'Other'.
    Identify which column, other than 'Living Expenses' correlates most with 'Living Expenses'
    and which column other than 'Other' correlates most with 'Other'.

    Return the names of each of those columns as a tuple.
    The first should be of the column corresponding to \li{'Living Expenses'} and the second to \li{'Other'}.
    
    Parameters:
        file (str): name of datafile
        
    Return:
        values (tuple): (name of column that most relates to Living Expenses, name of column that most relates to Other)
    """
    # Read in the CSV file
    df = pd.read_csv(file, index_col=0)
    
    # Fill NA values
    df = df.fillna(0.0)
    
    # Set new columns to sum of other columns
    df['Living Expenses'], df['Other'] = df['Rent'] + df['Groceries'] + df['Gas'] + df['Utilities'], df['Dining Out'] + df['Out With Friends'] + df['Netflix']

    # Create columns without living expenses and other
    l_e, other = list(df.columns), list(df.columns)
    l_e.remove('Living Expenses')
    other.remove('Other')
    
    # Filter by new columns then return the index max
    corr_le, corr_o = df.corr().filter(items=l_e, axis=0), df.corr().filter(items=other, axis=0)
    
    return (corr_le['Living Expenses'].idxmax(), corr_o['Other'].idxmax())
    
    
print(prob2())

('Rent', 'Dining Out')


# Problem 3

In [7]:
def prob3(file='crime_data.csv'):
    """
    Read in crime data and use pandas to answer the following questions.
    
    Set the index as the column 'Year', and return the answers to each question as a tuple.
    
    1) Identify the three crimes that have a mean over 1,500,000. 
    Of these three crimes, which two are very correlated? 
    Which of these two crimes has a greater maximum value?
    Save the title of this column as a variable to return as the answer.
    
    2) Examine the data since 2000.
    Sort this data (in ascending order) according to number of murders.
    Find the years where Aggravated Assault is greater than 850,000.
    Save the indices (the years) of the masked and reordered DataFrame as a NumPy array to return as the answer.
    
    3) What year had the highest crime rate? 
    In this year, which crime was committed the most? 
    What percentage of the total crime that year was it? 
    Save this value as a float.
    
    
    Parameters:
        file (str): data
    
    Return:
        ans_1 (string): answer to Question 1
        ans_2 (ndarray): answer to Question 2
        ans_3 (float): answer to Question 3
    """
    # Read in csv file
    df = pd.read_csv(file, index_col='Year')
    
    # Question 1
    means = df.iloc[:,2:].mean()
    mask = means >= 1500000
    columns = means[mask].index
    
    # Get the correlation matrix with mask applied to rows and columns
    corr = df.iloc[:,2:].corr()[mask].filter(items=list(columns),axis=1)
    new_mask = corr < 1
    
    # Get the two most correlated
    two_correlated = set(corr[new_mask].idxmax().ravel())
    
    # Find the max of the two most correlated
    max_1 = df.loc[:,list(two_correlated)[0]].max()
    max_2 = df.loc[:,list(two_correlated)[1]].max()
    
    # Set the answer to whichever max was higher
    answer_1 = list(two_correlated)[0] if max_1 > max_2 else list(two_correlated)[1]
    
    # Question 2
    this_millenium = df.loc[2000:].sort_values('Murder', ascending=True)
    answer_2 = np.array(this_millenium[this_millenium['Aggravated Assault'] > 850000].index)
    
    #Question 3
    df['Crime Rate'] = df['Total']/df['Population']
    highest = df['Crime Rate'].idxmax()
    answer_3 = df[list(set(df.columns) - set(['Population','Total']))].loc[highest].max()/df.loc[highest]['Total']
    
    return answer_1, answer_2, answer_3

print(prob3())

('Property', array([2000, 2001, 2002, 2003, 2005, 2007, 2006], dtype=int64), 0.8997188308734142)


# Problem 4

In [12]:
def prob4(file='DJIA.csv'):
    """

    Read the data with a DatetimeIndex as the index.
    Drop rows any rows without numerical values, cast the "VALUE" column to floats, then return the updated DataFrame.

    Parameters:
        file (str): data file
    Returns:
        df (DataFrame): updated DataFrame of stock market data
    """
    # Load Data
    df = pd.read_csv(file, index_col="DATE")
    
    # Convert index to datetime
    df.index = pd.to_datetime(df.index)
    new_df = df[pd.to_numeric(df['VALUE'], errors='coerce').notnull()]
    
    return new_df.astype(float)

display(prob4())

VALUE
DATE                
2006-09-27  11689.24
2006-09-28  11718.45
2006-09-29  11679.07
2006-10-02  11670.35
2006-10-03  11727.34
...              ...
2016-09-20  18129.96
2016-09-21  18293.70
2016-09-22  18392.46
2016-09-23  18261.45
2016-09-26  18094.83

[2517 rows x 1 columns]

# Problem 5

In [15]:
def prob5(file='paychecks.csv'):
    """

    Create data_range for index of paycheck data.

    Parameters:
        file (str): data file
    Returns:
        df (DataFrame): DataFrame of paycheck data
    """
    # Load Data
    df = pd.read_csv(file, names=['VALUE'])
    
    # Find the range
    ranges = pd.date_range(start='3/14/2008', freq='14D', periods=df.shape[0])
    df.index = ranges
    
    return df

display(prob5())

VALUE
2008-03-14  1122.26
2008-03-28   921.03
2008-04-11   962.46
2008-04-25  1035.97
2008-05-09  1078.59
...             ...
2011-07-29  1095.53
2011-08-12  1018.39
2011-08-26  1027.08
2011-09-09  1005.90
2011-09-23   963.29

[93 rows x 1 columns]

# Problem 6

In [17]:
def prob6(file='DJIA.csv'):
    """
    Compute the following information about the DJIA dataset
    1. The single day with the largest gain
    2. The single day with the largest loss

    Parameters:
        file (str): data file
    Returns:
        max_day (<M8[ns]): DateTimeIndex of maximum change
        min_day (<M8[ns]): DateTimeIndex of minimum change
    """
    # Load Data
    df = prob4(file)
    
    # Find the time difference for each value
    df['time'] = df['VALUE'].diff()
    max_day = df['time'].idxmax()
    min_day = df['time'].idxmin()
    
    return max_day, min_day

print(prob6())

(Timestamp('2008-10-13 00:00:00'), Timestamp('2008-09-29 00:00:00'))
